package de.i3mainz.flexgeo.portal.liferay.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the OGCService service. Represents a row in the &quot;olmaps_OGCService&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.i3mainz.flexgeo.portal.liferay.services.model.impl.OGCServiceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.i3mainz.flexgeo.portal.liferay.services.model.impl.OGCServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OGCService
 * @see de.i3mainz.flexgeo.portal.liferay.services.model.impl.OGCServiceImpl
 * @see de.i3mainz.flexgeo.portal.liferay.services.model.impl.OGCServiceModelImpl
 * @generated
 */
public interface OGCServiceModel extends BaseModel<OGCService>, StagedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a o g c service model instance should use the {@link OGCService} interface instead.
     */

    /**
     * Returns the primary key of this o g c service.
     *
     * @return the primary key of this o g c service
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this o g c service.
     *
     * @param primaryKey the primary key of this o g c service
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this o g c service.
     *
     * @return the uuid of this o g c service
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this o g c service.
     *
     * @param uuid the uuid of this o g c service
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the service ID of this o g c service.
     *
     * @return the service ID of this o g c service
     */
    public long getServiceId();

    /**
     * Sets the service ID of this o g c service.
     *
     * @param serviceId the service ID of this o g c service
     */
    public void setServiceId(long serviceId);

    /**
     * Returns the group ID of this o g c service.
     *
     * @return the group ID of this o g c service
     */
    public long getGroupId();

    /**
     * Sets the group ID of this o g c service.
     *
     * @param groupId the group ID of this o g c service
     */
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this o g c service.
     *
     * @return the company ID of this o g c service
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this o g c service.
     *
     * @param companyId the company ID of this o g c service
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this o g c service.
     *
     * @return the user ID of this o g c service
     */
    public long getUserId();

    /**
     * Sets the user ID of this o g c service.
     *
     * @param userId the user ID of this o g c service
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this o g c service.
     *
     * @return the user uuid of this o g c service
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this o g c service.
     *
     * @param userUuid the user uuid of this o g c service
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this o g c service.
     *
     * @return the create date of this o g c service
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this o g c service.
     *
     * @param createDate the create date of this o g c service
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this o g c service.
     *
     * @return the modified date of this o g c service
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this o g c service.
     *
     * @param modifiedDate the modified date of this o g c service
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the service name of this o g c service.
     *
     * @return the service name of this o g c service
     */
    @AutoEscape
    public String getServiceName();

    /**
     * Sets the service name of this o g c service.
     *
     * @param serviceName the service name of this o g c service
     */
    public void setServiceName(String serviceName);

    /**
     * Returns the service u r l of this o g c service.
     *
     * @return the service u r l of this o g c service
     */
    @AutoEscape
    public String getServiceURL();

    /**
     * Sets the service u r l of this o g c service.
     *
     * @param serviceURL the service u r l of this o g c service
     */
    public void setServiceURL(String serviceURL);

    /**
     * Returns the service type of this o g c service.
     *
     * @return the service type of this o g c service
     */
    @AutoEscape
    public String getServiceType();

    /**
     * Sets the service type of this o g c service.
     *
     * @param serviceType the service type of this o g c service
     */
    public void setServiceType(String serviceType);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(OGCService ogcService);

    @Override
    public int hashCode();

    @Override
    public CacheModel<OGCService> toCacheModel();

    @Override
    public OGCService toEscapedModel();

    @Override
    public OGCService toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
