package de.i3mainz.flexgeo.portal.liferay.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the OGCServiceLayer service. Represents a row in the &quot;olmaps_OGCServiceLayer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.i3mainz.flexgeo.portal.liferay.services.model.impl.OGCServiceLayerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.i3mainz.flexgeo.portal.liferay.services.model.impl.OGCServiceLayerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OGCServiceLayer
 * @see de.i3mainz.flexgeo.portal.liferay.services.model.impl.OGCServiceLayerImpl
 * @see de.i3mainz.flexgeo.portal.liferay.services.model.impl.OGCServiceLayerModelImpl
 * @generated
 */
public interface OGCServiceLayerModel extends BaseModel<OGCServiceLayer> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a o g c service layer model instance should use the {@link OGCServiceLayer} interface instead.
     */

    /**
     * Returns the primary key of this o g c service layer.
     *
     * @return the primary key of this o g c service layer
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this o g c service layer.
     *
     * @param primaryKey the primary key of this o g c service layer
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this o g c service layer.
     *
     * @return the uuid of this o g c service layer
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this o g c service layer.
     *
     * @param uuid the uuid of this o g c service layer
     */
    public void setUuid(String uuid);

    /**
     * Returns the layer ID of this o g c service layer.
     *
     * @return the layer ID of this o g c service layer
     */
    public long getLayerId();

    /**
     * Sets the layer ID of this o g c service layer.
     *
     * @param layerId the layer ID of this o g c service layer
     */
    public void setLayerId(long layerId);

    /**
     * Returns the group ID of this o g c service layer.
     *
     * @return the group ID of this o g c service layer
     */
    public long getGroupId();

    /**
     * Sets the group ID of this o g c service layer.
     *
     * @param groupId the group ID of this o g c service layer
     */
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this o g c service layer.
     *
     * @return the company ID of this o g c service layer
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this o g c service layer.
     *
     * @param companyId the company ID of this o g c service layer
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this o g c service layer.
     *
     * @return the user ID of this o g c service layer
     */
    public long getUserId();

    /**
     * Sets the user ID of this o g c service layer.
     *
     * @param userId the user ID of this o g c service layer
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this o g c service layer.
     *
     * @return the user uuid of this o g c service layer
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this o g c service layer.
     *
     * @param userUuid the user uuid of this o g c service layer
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this o g c service layer.
     *
     * @return the create date of this o g c service layer
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this o g c service layer.
     *
     * @param createDate the create date of this o g c service layer
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this o g c service layer.
     *
     * @return the modified date of this o g c service layer
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this o g c service layer.
     *
     * @param modifiedDate the modified date of this o g c service layer
     */
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the layer name of this o g c service layer.
     *
     * @return the layer name of this o g c service layer
     */
    @AutoEscape
    public String getLayerName();

    /**
     * Sets the layer name of this o g c service layer.
     *
     * @param layerName the layer name of this o g c service layer
     */
    public void setLayerName(String layerName);

    /**
     * Returns the layer service ID of this o g c service layer.
     *
     * @return the layer service ID of this o g c service layer
     */
    public long getLayerServiceId();

    /**
     * Sets the layer service ID of this o g c service layer.
     *
     * @param layerServiceId the layer service ID of this o g c service layer
     */
    public void setLayerServiceId(long layerServiceId);

    /**
     * Returns the layer options of this o g c service layer.
     *
     * @return the layer options of this o g c service layer
     */
    @AutoEscape
    public String getLayerOptions();

    /**
     * Sets the layer options of this o g c service layer.
     *
     * @param layerOptions the layer options of this o g c service layer
     */
    public void setLayerOptions(String layerOptions);

    /**
     * Returns the layer display options of this o g c service layer.
     *
     * @return the layer display options of this o g c service layer
     */
    @AutoEscape
    public String getLayerDisplayOptions();

    /**
     * Sets the layer display options of this o g c service layer.
     *
     * @param layerDisplayOptions the layer display options of this o g c service layer
     */
    public void setLayerDisplayOptions(String layerDisplayOptions);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(OGCServiceLayer ogcServiceLayer);

    public int hashCode();

    public CacheModel<OGCServiceLayer> toCacheModel();

    public OGCServiceLayer toEscapedModel();

    public String toString();

    public String toXmlString();
}
