package de.i3mainz.flexgeo.portal.liferay.services.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.CompanyPersistence;
import com.liferay.portal.service.persistence.GroupPersistence;
import com.liferay.portal.service.persistence.OrganizationPersistence;
import com.liferay.portal.service.persistence.PortletPreferencesPersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import de.i3mainz.flexgeo.portal.liferay.services.model.OGCService;
import de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceService;
import de.i3mainz.flexgeo.portal.liferay.services.service.persistence.OGCServiceLayerPersistence;
import de.i3mainz.flexgeo.portal.liferay.services.service.persistence.OGCServicePersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the o g c service remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link de.i3mainz.flexgeo.portal.liferay.services.service.impl.OGCServiceServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see de.i3mainz.flexgeo.portal.liferay.services.service.impl.OGCServiceServiceImpl
 * @see de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceServiceUtil
 * @generated
 */
public abstract class OGCServiceServiceBaseImpl extends BaseServiceImpl
    implements OGCServiceService, IdentifiableBean {
    @BeanReference(type = de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceLocalService.class)
    protected de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceLocalService ogcServiceLocalService;
    @BeanReference(type = de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceService.class)
    protected de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceService ogcServiceService;
    @BeanReference(type = OGCServicePersistence.class)
    protected OGCServicePersistence ogcServicePersistence;
    @BeanReference(type = de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceLayerLocalService.class)
    protected de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceLayerLocalService ogcServiceLayerLocalService;
    @BeanReference(type = de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceLayerService.class)
    protected de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceLayerService ogcServiceLayerService;
    @BeanReference(type = OGCServiceLayerPersistence.class)
    protected OGCServiceLayerPersistence ogcServiceLayerPersistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.CompanyLocalService.class)
    protected com.liferay.portal.service.CompanyLocalService companyLocalService;
    @BeanReference(type = com.liferay.portal.service.CompanyService.class)
    protected com.liferay.portal.service.CompanyService companyService;
    @BeanReference(type = CompanyPersistence.class)
    protected CompanyPersistence companyPersistence;
    @BeanReference(type = com.liferay.portal.service.GroupLocalService.class)
    protected com.liferay.portal.service.GroupLocalService groupLocalService;
    @BeanReference(type = com.liferay.portal.service.GroupService.class)
    protected com.liferay.portal.service.GroupService groupService;
    @BeanReference(type = GroupPersistence.class)
    protected GroupPersistence groupPersistence;
    @BeanReference(type = com.liferay.portal.service.OrganizationLocalService.class)
    protected com.liferay.portal.service.OrganizationLocalService organizationLocalService;
    @BeanReference(type = com.liferay.portal.service.OrganizationService.class)
    protected com.liferay.portal.service.OrganizationService organizationService;
    @BeanReference(type = OrganizationPersistence.class)
    protected OrganizationPersistence organizationPersistence;
    @BeanReference(type = com.liferay.portal.service.PortletPreferencesLocalService.class)
    protected com.liferay.portal.service.PortletPreferencesLocalService portletPreferencesLocalService;
    @BeanReference(type = com.liferay.portal.service.PortletPreferencesService.class)
    protected com.liferay.portal.service.PortletPreferencesService portletPreferencesService;
    @BeanReference(type = PortletPreferencesPersistence.class)
    protected PortletPreferencesPersistence portletPreferencesPersistence;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private OGCServiceServiceClpInvoker _clpInvoker = new OGCServiceServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceServiceUtil} to access the o g c service remote service.
     */

    /**
     * Returns the o g c service local service.
     *
     * @return the o g c service local service
     */
    public de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceLocalService getOGCServiceLocalService() {
        return ogcServiceLocalService;
    }

    /**
     * Sets the o g c service local service.
     *
     * @param ogcServiceLocalService the o g c service local service
     */
    public void setOGCServiceLocalService(
        de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceLocalService ogcServiceLocalService) {
        this.ogcServiceLocalService = ogcServiceLocalService;
    }

    /**
     * Returns the o g c service remote service.
     *
     * @return the o g c service remote service
     */
    public de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceService getOGCServiceService() {
        return ogcServiceService;
    }

    /**
     * Sets the o g c service remote service.
     *
     * @param ogcServiceService the o g c service remote service
     */
    public void setOGCServiceService(
        de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceService ogcServiceService) {
        this.ogcServiceService = ogcServiceService;
    }

    /**
     * Returns the o g c service persistence.
     *
     * @return the o g c service persistence
     */
    public OGCServicePersistence getOGCServicePersistence() {
        return ogcServicePersistence;
    }

    /**
     * Sets the o g c service persistence.
     *
     * @param ogcServicePersistence the o g c service persistence
     */
    public void setOGCServicePersistence(
        OGCServicePersistence ogcServicePersistence) {
        this.ogcServicePersistence = ogcServicePersistence;
    }

    /**
     * Returns the o g c service layer local service.
     *
     * @return the o g c service layer local service
     */
    public de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceLayerLocalService getOGCServiceLayerLocalService() {
        return ogcServiceLayerLocalService;
    }

    /**
     * Sets the o g c service layer local service.
     *
     * @param ogcServiceLayerLocalService the o g c service layer local service
     */
    public void setOGCServiceLayerLocalService(
        de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceLayerLocalService ogcServiceLayerLocalService) {
        this.ogcServiceLayerLocalService = ogcServiceLayerLocalService;
    }

    /**
     * Returns the o g c service layer remote service.
     *
     * @return the o g c service layer remote service
     */
    public de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceLayerService getOGCServiceLayerService() {
        return ogcServiceLayerService;
    }

    /**
     * Sets the o g c service layer remote service.
     *
     * @param ogcServiceLayerService the o g c service layer remote service
     */
    public void setOGCServiceLayerService(
        de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceLayerService ogcServiceLayerService) {
        this.ogcServiceLayerService = ogcServiceLayerService;
    }

    /**
     * Returns the o g c service layer persistence.
     *
     * @return the o g c service layer persistence
     */
    public OGCServiceLayerPersistence getOGCServiceLayerPersistence() {
        return ogcServiceLayerPersistence;
    }

    /**
     * Sets the o g c service layer persistence.
     *
     * @param ogcServiceLayerPersistence the o g c service layer persistence
     */
    public void setOGCServiceLayerPersistence(
        OGCServiceLayerPersistence ogcServiceLayerPersistence) {
        this.ogcServiceLayerPersistence = ogcServiceLayerPersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the company local service.
     *
     * @return the company local service
     */
    public com.liferay.portal.service.CompanyLocalService getCompanyLocalService() {
        return companyLocalService;
    }

    /**
     * Sets the company local service.
     *
     * @param companyLocalService the company local service
     */
    public void setCompanyLocalService(
        com.liferay.portal.service.CompanyLocalService companyLocalService) {
        this.companyLocalService = companyLocalService;
    }

    /**
     * Returns the company remote service.
     *
     * @return the company remote service
     */
    public com.liferay.portal.service.CompanyService getCompanyService() {
        return companyService;
    }

    /**
     * Sets the company remote service.
     *
     * @param companyService the company remote service
     */
    public void setCompanyService(
        com.liferay.portal.service.CompanyService companyService) {
        this.companyService = companyService;
    }

    /**
     * Returns the company persistence.
     *
     * @return the company persistence
     */
    public CompanyPersistence getCompanyPersistence() {
        return companyPersistence;
    }

    /**
     * Sets the company persistence.
     *
     * @param companyPersistence the company persistence
     */
    public void setCompanyPersistence(CompanyPersistence companyPersistence) {
        this.companyPersistence = companyPersistence;
    }

    /**
     * Returns the group local service.
     *
     * @return the group local service
     */
    public com.liferay.portal.service.GroupLocalService getGroupLocalService() {
        return groupLocalService;
    }

    /**
     * Sets the group local service.
     *
     * @param groupLocalService the group local service
     */
    public void setGroupLocalService(
        com.liferay.portal.service.GroupLocalService groupLocalService) {
        this.groupLocalService = groupLocalService;
    }

    /**
     * Returns the group remote service.
     *
     * @return the group remote service
     */
    public com.liferay.portal.service.GroupService getGroupService() {
        return groupService;
    }

    /**
     * Sets the group remote service.
     *
     * @param groupService the group remote service
     */
    public void setGroupService(
        com.liferay.portal.service.GroupService groupService) {
        this.groupService = groupService;
    }

    /**
     * Returns the group persistence.
     *
     * @return the group persistence
     */
    public GroupPersistence getGroupPersistence() {
        return groupPersistence;
    }

    /**
     * Sets the group persistence.
     *
     * @param groupPersistence the group persistence
     */
    public void setGroupPersistence(GroupPersistence groupPersistence) {
        this.groupPersistence = groupPersistence;
    }

    /**
     * Returns the organization local service.
     *
     * @return the organization local service
     */
    public com.liferay.portal.service.OrganizationLocalService getOrganizationLocalService() {
        return organizationLocalService;
    }

    /**
     * Sets the organization local service.
     *
     * @param organizationLocalService the organization local service
     */
    public void setOrganizationLocalService(
        com.liferay.portal.service.OrganizationLocalService organizationLocalService) {
        this.organizationLocalService = organizationLocalService;
    }

    /**
     * Returns the organization remote service.
     *
     * @return the organization remote service
     */
    public com.liferay.portal.service.OrganizationService getOrganizationService() {
        return organizationService;
    }

    /**
     * Sets the organization remote service.
     *
     * @param organizationService the organization remote service
     */
    public void setOrganizationService(
        com.liferay.portal.service.OrganizationService organizationService) {
        this.organizationService = organizationService;
    }

    /**
     * Returns the organization persistence.
     *
     * @return the organization persistence
     */
    public OrganizationPersistence getOrganizationPersistence() {
        return organizationPersistence;
    }

    /**
     * Sets the organization persistence.
     *
     * @param organizationPersistence the organization persistence
     */
    public void setOrganizationPersistence(
        OrganizationPersistence organizationPersistence) {
        this.organizationPersistence = organizationPersistence;
    }

    /**
     * Returns the portlet preferences local service.
     *
     * @return the portlet preferences local service
     */
    public com.liferay.portal.service.PortletPreferencesLocalService getPortletPreferencesLocalService() {
        return portletPreferencesLocalService;
    }

    /**
     * Sets the portlet preferences local service.
     *
     * @param portletPreferencesLocalService the portlet preferences local service
     */
    public void setPortletPreferencesLocalService(
        com.liferay.portal.service.PortletPreferencesLocalService portletPreferencesLocalService) {
        this.portletPreferencesLocalService = portletPreferencesLocalService;
    }

    /**
     * Returns the portlet preferences remote service.
     *
     * @return the portlet preferences remote service
     */
    public com.liferay.portal.service.PortletPreferencesService getPortletPreferencesService() {
        return portletPreferencesService;
    }

    /**
     * Sets the portlet preferences remote service.
     *
     * @param portletPreferencesService the portlet preferences remote service
     */
    public void setPortletPreferencesService(
        com.liferay.portal.service.PortletPreferencesService portletPreferencesService) {
        this.portletPreferencesService = portletPreferencesService;
    }

    /**
     * Returns the portlet preferences persistence.
     *
     * @return the portlet preferences persistence
     */
    public PortletPreferencesPersistence getPortletPreferencesPersistence() {
        return portletPreferencesPersistence;
    }

    /**
     * Sets the portlet preferences persistence.
     *
     * @param portletPreferencesPersistence the portlet preferences persistence
     */
    public void setPortletPreferencesPersistence(
        PortletPreferencesPersistence portletPreferencesPersistence) {
        this.portletPreferencesPersistence = portletPreferencesPersistence;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();
    }

    public void destroy() {
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return OGCService.class;
    }

    protected String getModelClassName() {
        return OGCService.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = ogcServicePersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
