package de.i3mainz.flexgeo.portal.liferay.services.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.i3mainz.flexgeo.portal.liferay.services.model.OGCService;
import de.i3mainz.flexgeo.portal.liferay.services.service.OGCServiceLocalServiceUtil;

/**
 * The extended model base implementation for the OGCService service. Represents a row in the &quot;olmaps_OGCService&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OGCServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OGCServiceImpl
 * @see de.i3mainz.flexgeo.portal.liferay.services.model.OGCService
 * @generated
 */
public abstract class OGCServiceBaseImpl extends OGCServiceModelImpl
    implements OGCService {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a o g c service model instance should use the {@link OGCService} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            OGCServiceLocalServiceUtil.addOGCService(this);
        } else {
            OGCServiceLocalServiceUtil.updateOGCService(this);
        }
    }
}
