package de.i3mainz.flexgeo.portal.liferay.services.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.i3mainz.flexgeo.portal.liferay.services.model.OGCService;
import de.i3mainz.flexgeo.portal.liferay.services.model.OGCServiceModel;
import de.i3mainz.flexgeo.portal.liferay.services.model.OGCServiceSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the OGCService service. Represents a row in the &quot;olmaps_OGCService&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.i3mainz.flexgeo.portal.liferay.services.model.OGCServiceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OGCServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OGCServiceImpl
 * @see de.i3mainz.flexgeo.portal.liferay.services.model.OGCService
 * @see de.i3mainz.flexgeo.portal.liferay.services.model.OGCServiceModel
 * @generated
 */
@JSON(strict = true)
public class OGCServiceModelImpl extends BaseModelImpl<OGCService>
    implements OGCServiceModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a o g c service model instance should use the {@link de.i3mainz.flexgeo.portal.liferay.services.model.OGCService} interface instead.
     */
    public static final String TABLE_NAME = "olmaps_OGCService";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "serviceId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "serviceName", Types.VARCHAR },
            { "serviceURL", Types.VARCHAR },
            { "serviceType", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table olmaps_OGCService (uuid_ VARCHAR(75) null,serviceId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,serviceName VARCHAR(75) null,serviceURL VARCHAR(75) null,serviceType VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table olmaps_OGCService";
    public static final String ORDER_BY_JPQL = " ORDER BY ogcService.serviceId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY olmaps_OGCService.serviceId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.de.i3mainz.flexgeo.portal.liferay.services.model.OGCService"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.de.i3mainz.flexgeo.portal.liferay.services.model.OGCService"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.de.i3mainz.flexgeo.portal.liferay.services.model.OGCService"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static long GROUPID_COLUMN_BITMASK = 2L;
    public static long SERVICETYPE_COLUMN_BITMASK = 4L;
    public static long UUID_COLUMN_BITMASK = 8L;
    public static long SERVICEID_COLUMN_BITMASK = 16L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.de.i3mainz.flexgeo.portal.liferay.services.model.OGCService"));
    private static ClassLoader _classLoader = OGCService.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            OGCService.class
        };
    private String _uuid;
    private String _originalUuid;
    private long _serviceId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private Date _createDate;
    private Date _modifiedDate;
    private String _serviceName;
    private String _serviceURL;
    private String _serviceType;
    private String _originalServiceType;
    private long _columnBitmask;
    private OGCService _escapedModel;

    public OGCServiceModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static OGCService toModel(OGCServiceSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        OGCService model = new OGCServiceImpl();

        model.setUuid(soapModel.getUuid());
        model.setServiceId(soapModel.getServiceId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setServiceName(soapModel.getServiceName());
        model.setServiceURL(soapModel.getServiceURL());
        model.setServiceType(soapModel.getServiceType());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<OGCService> toModels(OGCServiceSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<OGCService> models = new ArrayList<OGCService>(soapModels.length);

        for (OGCServiceSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _serviceId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setServiceId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _serviceId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return OGCService.class;
    }

    @Override
    public String getModelClassName() {
        return OGCService.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("serviceId", getServiceId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("serviceName", getServiceName());
        attributes.put("serviceURL", getServiceURL());
        attributes.put("serviceType", getServiceType());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long serviceId = (Long) attributes.get("serviceId");

        if (serviceId != null) {
            setServiceId(serviceId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String serviceName = (String) attributes.get("serviceName");

        if (serviceName != null) {
            setServiceName(serviceName);
        }

        String serviceURL = (String) attributes.get("serviceURL");

        if (serviceURL != null) {
            setServiceURL(serviceURL);
        }

        String serviceType = (String) attributes.get("serviceType");

        if (serviceType != null) {
            setServiceType(serviceType);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getServiceId() {
        return _serviceId;
    }

    @Override
    public void setServiceId(long serviceId) {
        _columnBitmask = -1L;

        _serviceId = serviceId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public String getServiceName() {
        if (_serviceName == null) {
            return StringPool.BLANK;
        } else {
            return _serviceName;
        }
    }

    @Override
    public void setServiceName(String serviceName) {
        _serviceName = serviceName;
    }

    @JSON
    @Override
    public String getServiceURL() {
        if (_serviceURL == null) {
            return StringPool.BLANK;
        } else {
            return _serviceURL;
        }
    }

    @Override
    public void setServiceURL(String serviceURL) {
        _serviceURL = serviceURL;
    }

    @JSON
    @Override
    public String getServiceType() {
        if (_serviceType == null) {
            return StringPool.BLANK;
        } else {
            return _serviceType;
        }
    }

    @Override
    public void setServiceType(String serviceType) {
        _columnBitmask |= SERVICETYPE_COLUMN_BITMASK;

        if (_originalServiceType == null) {
            _originalServiceType = _serviceType;
        }

        _serviceType = serviceType;
    }

    public String getOriginalServiceType() {
        return GetterUtil.getString(_originalServiceType);
    }

    @Override
    public StagedModelType getStagedModelType() {
        return new StagedModelType(PortalUtil.getClassNameId(
                OGCService.class.getName()));
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            OGCService.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public OGCService toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (OGCService) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        OGCServiceImpl ogcServiceImpl = new OGCServiceImpl();

        ogcServiceImpl.setUuid(getUuid());
        ogcServiceImpl.setServiceId(getServiceId());
        ogcServiceImpl.setGroupId(getGroupId());
        ogcServiceImpl.setCompanyId(getCompanyId());
        ogcServiceImpl.setUserId(getUserId());
        ogcServiceImpl.setCreateDate(getCreateDate());
        ogcServiceImpl.setModifiedDate(getModifiedDate());
        ogcServiceImpl.setServiceName(getServiceName());
        ogcServiceImpl.setServiceURL(getServiceURL());
        ogcServiceImpl.setServiceType(getServiceType());

        ogcServiceImpl.resetOriginalValues();

        return ogcServiceImpl;
    }

    @Override
    public int compareTo(OGCService ogcService) {
        int value = 0;

        if (getServiceId() < ogcService.getServiceId()) {
            value = -1;
        } else if (getServiceId() > ogcService.getServiceId()) {
            value = 1;
        } else {
            value = 0;
        }

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof OGCService)) {
            return false;
        }

        OGCService ogcService = (OGCService) obj;

        long primaryKey = ogcService.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        OGCServiceModelImpl ogcServiceModelImpl = this;

        ogcServiceModelImpl._originalUuid = ogcServiceModelImpl._uuid;

        ogcServiceModelImpl._originalGroupId = ogcServiceModelImpl._groupId;

        ogcServiceModelImpl._setOriginalGroupId = false;

        ogcServiceModelImpl._originalCompanyId = ogcServiceModelImpl._companyId;

        ogcServiceModelImpl._setOriginalCompanyId = false;

        ogcServiceModelImpl._originalServiceType = ogcServiceModelImpl._serviceType;

        ogcServiceModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<OGCService> toCacheModel() {
        OGCServiceCacheModel ogcServiceCacheModel = new OGCServiceCacheModel();

        ogcServiceCacheModel.uuid = getUuid();

        String uuid = ogcServiceCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            ogcServiceCacheModel.uuid = null;
        }

        ogcServiceCacheModel.serviceId = getServiceId();

        ogcServiceCacheModel.groupId = getGroupId();

        ogcServiceCacheModel.companyId = getCompanyId();

        ogcServiceCacheModel.userId = getUserId();

        Date createDate = getCreateDate();

        if (createDate != null) {
            ogcServiceCacheModel.createDate = createDate.getTime();
        } else {
            ogcServiceCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            ogcServiceCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            ogcServiceCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        ogcServiceCacheModel.serviceName = getServiceName();

        String serviceName = ogcServiceCacheModel.serviceName;

        if ((serviceName != null) && (serviceName.length() == 0)) {
            ogcServiceCacheModel.serviceName = null;
        }

        ogcServiceCacheModel.serviceURL = getServiceURL();

        String serviceURL = ogcServiceCacheModel.serviceURL;

        if ((serviceURL != null) && (serviceURL.length() == 0)) {
            ogcServiceCacheModel.serviceURL = null;
        }

        ogcServiceCacheModel.serviceType = getServiceType();

        String serviceType = ogcServiceCacheModel.serviceType;

        if ((serviceType != null) && (serviceType.length() == 0)) {
            ogcServiceCacheModel.serviceType = null;
        }

        return ogcServiceCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(21);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", serviceId=");
        sb.append(getServiceId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", serviceName=");
        sb.append(getServiceName());
        sb.append(", serviceURL=");
        sb.append(getServiceURL());
        sb.append(", serviceType=");
        sb.append(getServiceType());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(34);

        sb.append("<model><model-name>");
        sb.append("de.i3mainz.flexgeo.portal.liferay.services.model.OGCService");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>serviceId</column-name><column-value><![CDATA[");
        sb.append(getServiceId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>serviceName</column-name><column-value><![CDATA[");
        sb.append(getServiceName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>serviceURL</column-name><column-value><![CDATA[");
        sb.append(getServiceURL());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>serviceType</column-name><column-value><![CDATA[");
        sb.append(getServiceType());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
